package:
    type:           project
    name:           hiam
    title:          This is AHnames realization of HIAM
    headline:       AHnames HIAM
    keywords:       ahnames, hiam, login, access management
    namespace:      ahnames\hiam
    src:            ''

require:
    hiqdev/hidev-php:     "*"
    ahnames/hidev-vendor: "*@dev"
