package:
    name:           hiam
    label:          AHnamesHIAM
    title:          AHnames HIAM
    type:           project
    homepage:       https://ahnames.com/
    keywords:       ahnames, hiam, login, access management
    year:           2015
    description:    This is AHnames realization of HIAM

require:
    ahnames/hidev-config:       "*"
    hiqdev/hidev-config-php:    "*"
